apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "flask-deployment"
  namespace: "default"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: "flask"
    spec:
      containers:
      - image: peterwatt/flaskdemo
        imagePullPolicy: Always
        name: "flask"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
  name: "flask-service"
  namespace: "default"
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: NodePort
  selector:
    app: "flask"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "flask-ingress"
  namespace: "default"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: flask-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: "flask-service"
          servicePort: 5000
